#!/bin/bash
# Quick start guide

echo "MLOps AKS Deployment - Quick Start"
echo "===================================="
echo ""
echo "Prerequisites:"
echo "  - Azure CLI (az command)"
echo "  - kubectl"
echo "  - Docker"
echo ""
echo "Steps:"
echo ""
echo "1. Setup Azure & AKS:"
echo "   bash scripts/setup-aks.sh"
echo ""
echo "2. Build and push Docker images:"
echo "   az acr login --name myregistry"
echo "   docker build -f Dockerfile.training -t myregistry.azurecr.io/mlops-training:latest ."
echo "   docker push myregistry.azurecr.io/mlops-training:latest"
echo "   docker build -f Dockerfile.serving -t myregistry.azurecr.io/mlops-serving:latest ."
echo "   docker push myregistry.azurecr.io/mlops-serving:latest"
echo ""
echo "3. Deploy to AKS:"
echo "   bash scripts/deploy.sh"
echo ""
echo "4. Test the deployment:"
echo "   bash scripts/test-inference.sh"
echo ""
